# Generated by Django 5.0.3 on 2024-04-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_img', models.ImageField(upload_to='media/ProfileImg')),
                ('Name', models.CharField(max_length=100)),
                ('Profession1', models.CharField(max_length=100)),
                ('Profession2', models.CharField(max_length=100)),
                ('Profession3', models.CharField(max_length=100)),
                ('About_details', models.CharField(max_length=500)),
                ('Profession_title1', models.CharField(max_length=100)),
                ('Profession_title2', models.CharField(max_length=100)),
                ('Profession_details', models.CharField(max_length=500)),
                ('Profession_para', models.CharField(max_length=500)),
                ('Birthday', models.CharField(max_length=100)),
                ('Website', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Freelance_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_para', models.CharField(max_length=500)),
                ('Contact_location', models.CharField(max_length=100)),
                ('Contact_Email', models.CharField(max_length=100)),
                ('Contact_Call', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='factModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fact_para', models.CharField(max_length=500)),
                ('Happy_clients', models.CharField(max_length=100)),
                ('Projects', models.CharField(max_length=100)),
                ('Hours_of_support', models.CharField(max_length=100)),
                ('Hard_workers', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Portfolio_para', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeEducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Education_name', models.CharField(max_length=100)),
                ('Education_year', models.CharField(max_length=100)),
                ('Education_institute', models.CharField(max_length=100)),
                ('Education_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resume_para', models.CharField(max_length=500)),
                ('Name', models.CharField(max_length=100)),
                ('About', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeProfessionalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Professional_experience', models.CharField(max_length=100)),
                ('Professional_experience_year', models.CharField(max_length=100)),
                ('Professional_experience_location', models.CharField(max_length=100)),
                ('Professional_responsibilities', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Services_para', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_icon', models.CharField(max_length=100)),
                ('Service_name', models.CharField(max_length=100)),
                ('Service_details', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SkillMatricesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill_name', models.CharField(max_length=100)),
                ('Skill_progressbar', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill_para', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('Instagram', models.CharField(max_length=100)),
                ('skype', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Testimonial_para', models.CharField(max_length=500)),
                ('Client_name', models.CharField(max_length=100)),
                ('Client_img', models.ImageField(upload_to='media/ClientImg')),
                ('Client_profession', models.CharField(max_length=100)),
                ('Client_quote', models.CharField(max_length=500)),
            ],
        ),
    ]
