# Generated by Django 5.0.6 on 2024-05-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0002_alter_customusermodel_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='user_type',
            field=models.CharField(choices=[('3', 'student'), ('1', 'admin'), ('2', 'teacher')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentaddmodel',
            name='Gender',
            field=models.CharField(choices=[('others', 'Others'), ('male', 'Male'), ('female', 'Female')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentaddmodel',
            name='Section',
            field=models.CharField(choices=[('3', 'C'), ('4', 'D'), ('1', 'A'), ('2', 'B')], max_length=100),
        ),
    ]
