# Generated by Django 5.0.6 on 2024-05-30 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0004_alter_customusermodel_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='user_type',
            field=models.CharField(choices=[('2', 'teacher'), ('1', 'admin'), ('3', 'student')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentaddmodel',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentaddmodel',
            name='Section',
            field=models.CharField(choices=[('2', 'B'), ('1', 'A'), ('3', 'C'), ('4', 'D')], max_length=100),
        ),
        migrations.AlterField(
            model_name='teacheraddmodel',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='teacheraddmodel',
            name='qualification',
            field=models.CharField(choices=[('bsc', 'BSc. in CSE'), ('msc', 'MSc. in CSE')], max_length=100),
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.CharField(max_length=100)),
                ('sub_name', models.CharField(max_length=100)),
                ('myDepartment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schoolApp.departmentaddmodel')),
            ],
        ),
    ]
