# Generated by Django 5.0.3 on 2024-04-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTestimonialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_name', models.CharField(max_length=100)),
                ('Client_img', models.ImageField(upload_to='media/ClientImg')),
                ('Client_profession', models.CharField(max_length=100)),
                ('Client_quote', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='testimonialmodel',
            name='Client_img',
        ),
        migrations.RemoveField(
            model_name='testimonialmodel',
            name='Client_name',
        ),
        migrations.RemoveField(
            model_name='testimonialmodel',
            name='Client_profession',
        ),
        migrations.RemoveField(
            model_name='testimonialmodel',
            name='Client_quote',
        ),
    ]
