# Generated by Django 5.0.6 on 2024-06-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0005_alter_applyjobmodel_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjobmodel',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='user_type',
            field=models.CharField(choices=[('recruiter', 'Job Recruiter'), ('seeker', 'Job Seeker')], max_length=100),
        ),
    ]
