# Generated by Django 5.0.6 on 2024-05-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='user_type',
            field=models.CharField(choices=[('1', 'admin'), ('3', 'student'), ('2', 'teacher')], max_length=100),
        ),
    ]
