# Generated by Django 5.0.6 on 2024-05-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='user_type',
            field=models.CharField(choices=[('2', 'teacher'), ('3', 'student'), ('1', 'admin')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentaddmodel',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('others', 'Others'), ('female', 'Female')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentaddmodel',
            name='Section',
            field=models.CharField(choices=[('1', 'A'), ('3', 'C'), ('2', 'B'), ('4', 'D')], max_length=100),
        ),
    ]
