# Generated by Django 5.0.6 on 2024-05-28 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0003_alter_customusermodel_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='user_type',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'teacher'), ('3', 'student')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentaddmodel',
            name='Gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentaddmodel',
            name='Section',
            field=models.CharField(choices=[('4', 'D'), ('3', 'C'), ('2', 'B'), ('1', 'A')], max_length=100),
        ),
        migrations.CreateModel(
            name='TeacherAddModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('others', 'Others')], max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('qualification', models.CharField(choices=[('msc', 'MSc. in CSE'), ('bsc', 'BSc. in CSE')], max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to='static/teacher_img')),
                ('present_address', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=100)),
                ('myDepartment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schoolApp.departmentaddmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
