# Generated by Django 5.0.6 on 2024-06-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='user_type',
            field=models.CharField(choices=[('seeker', 'Job Seeker'), ('recruiter', 'Job Recruiter')], max_length=100, null=True),
        ),
    ]
