# Generated by Django 5.0.6 on 2024-06-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaloryCounterApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='gender',
            field=models.CharField(choices=[('others', 'Others'), ('male', 'Male'), ('female', 'Female')], max_length=100),
        ),
    ]
